import { IMG } from './images';

/**
 * The ALAAP menu. Prices are whole rupees and follow one coherent strategy:
 * espresso-forward drinks ₹150–260, milk-and-syrup builds ₹250–300, breakfast
 * ₹340–450, mains ₹380–540, bakery ₹150–230, desserts ₹280–350 — positioned
 * against specialty cafés in Indiranagar, Bandra and Jubilee Hills.
 */

export type ModifierKey =
  | 'size'
  | 'milk'
  | 'coffeeAddons'
  | 'sweetness'
  | 'iceLevel'
  | 'teaStrength'
  | 'matchaAddons'
  | 'toastAddons'
  | 'bread'
  | 'eggStyle'
  | 'pastaAddons'
  | 'pastaSpice'
  | 'sandwichAddons'
  | 'saladDressing'
  | 'saladAddons'
  | 'dessertAddons';

export interface SeedProduct {
  name: string;
  slug: string;
  description: string;
  story?: string;
  basePrice: number;
  image: string;
  calories?: number;
  prepTimeMinutes?: number;
  ingredients: string[];
  allergens?: string[];
  tags: string[];
  nonVeg?: boolean;
  vegan?: boolean;
  egg?: boolean;
  nuts?: boolean;
  gluten?: boolean;
  spicy?: boolean;
  bestseller?: boolean;
  isNew?: boolean;
  chefSpecial?: boolean;
  seasonal?: boolean;
  rating?: number;
  ratingCount?: number;
  orderCount?: number;
  modifiers: ModifierKey[];
}

export interface SeedCategory {
  name: string;
  slug: string;
  description: string;
  image: string;
  products: SeedProduct[];
}

const COFFEE_MODS: ModifierKey[] = ['size', 'milk', 'sweetness', 'coffeeAddons'];
const BLACK_COFFEE_MODS: ModifierKey[] = ['size', 'sweetness', 'coffeeAddons'];
const COLD_MODS: ModifierKey[] = ['size', 'milk', 'sweetness', 'iceLevel', 'coffeeAddons'];

export const MENU: SeedCategory[] = [
  // ─────────────────────────────────────────────────────────── Coffee
  {
    name: 'Coffee',
    slug: 'coffee',
    description: 'Pulled on a three-group lever machine, from beans roasted eleven days ago or fewer.',
    image: IMG.latte,
    products: [
      {
        name: 'Espresso',
        slug: 'espresso',
        description: 'A single 30ml shot of our house blend — cocoa, dried fig, a long caramel finish.',
        story:
          'Our house espresso is 70% Attikan Estate arabica from Chikmagalur and 30% washed Ethiopian Guji. We pull it slightly under 9 bars for a rounder, less brittle shot.',
        basePrice: 150,
        image: IMG.espresso,
        calories: 5,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'filtered water'],
        tags: ['coffee', 'espresso', 'hot', 'strong', 'classic'],
        vegan: true,
        rating: 4.7,
        ratingCount: 214,
        orderCount: 1840,
        modifiers: BLACK_COFFEE_MODS,
      },
      {
        name: 'Double Espresso',
        slug: 'double-espresso',
        description: 'Two shots, pulled together. For the mornings that need a firmer hand.',
        basePrice: 180,
        image: IMG.espressoDouble,
        calories: 10,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'filtered water'],
        tags: ['coffee', 'espresso', 'hot', 'strong', 'doppio'],
        vegan: true,
        rating: 4.6,
        ratingCount: 132,
        orderCount: 910,
        modifiers: BLACK_COFFEE_MODS,
      },
      {
        name: 'Americano',
        slug: 'americano',
        description: 'Espresso lengthened with hot water, poured shot-last to keep the crema intact.',
        basePrice: 190,
        image: IMG.americano,
        calories: 15,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'filtered water'],
        tags: ['coffee', 'black', 'hot', 'americano'],
        vegan: true,
        rating: 4.5,
        ratingCount: 168,
        orderCount: 1120,
        modifiers: BLACK_COFFEE_MODS,
      },
      {
        name: 'Cappuccino',
        slug: 'cappuccino',
        description: 'Equal parts espresso, steamed milk and a dense, sweet foam. Dusted only if you ask.',
        story: 'Textured to 62°C — hot enough to comfort, cool enough that the milk still tastes of milk.',
        basePrice: 210,
        image: IMG.cappuccino,
        calories: 130,
        prepTimeMinutes: 5,
        ingredients: ['house espresso blend', 'whole milk'],
        allergens: ['Milk'],
        tags: ['coffee', 'milk', 'hot', 'cappuccino', 'classic'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 486,
        orderCount: 3210,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Café Latte',
        slug: 'cafe-latte',
        description: 'A long, soft milk drink built on a double shot, with a thin cap of microfoam.',
        basePrice: 220,
        image: IMG.latte,
        calories: 190,
        prepTimeMinutes: 5,
        ingredients: ['house espresso blend', 'whole milk'],
        allergens: ['Milk'],
        tags: ['coffee', 'milk', 'hot', 'latte', 'mild'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 402,
        orderCount: 2980,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Flat White',
        slug: 'flat-white',
        description: 'Ristretto-forward and 160ml short, so the coffee stays in front of the milk.',
        basePrice: 230,
        image: IMG.flatWhite,
        calories: 155,
        prepTimeMinutes: 5,
        ingredients: ['house espresso blend', 'whole milk'],
        allergens: ['Milk'],
        tags: ['coffee', 'milk', 'hot', 'flat white', 'strong'],
        bestseller: true,
        chefSpecial: true,
        rating: 4.9,
        ratingCount: 356,
        orderCount: 2640,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Cortado',
        slug: 'cortado',
        description: 'A double ristretto cut with an equal measure of warm milk. Served in glass.',
        basePrice: 210,
        image: IMG.cortado,
        calories: 90,
        prepTimeMinutes: 5,
        ingredients: ['house espresso blend', 'whole milk'],
        allergens: ['Milk'],
        tags: ['coffee', 'milk', 'hot', 'cortado', 'strong'],
        rating: 4.7,
        ratingCount: 184,
        orderCount: 1290,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Mocha',
        slug: 'mocha',
        description: '65% single-origin couverture melted into espresso, finished with steamed milk.',
        basePrice: 260,
        image: IMG.mocha,
        calories: 290,
        prepTimeMinutes: 6,
        ingredients: ['house espresso blend', 'whole milk', '65% dark chocolate', 'cocoa'],
        allergens: ['Milk'],
        tags: ['coffee', 'chocolate', 'hot', 'mocha', 'sweet'],
        rating: 4.6,
        ratingCount: 268,
        orderCount: 1760,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Macchiato',
        slug: 'macchiato',
        description: 'Espresso marked with a spoon of foam — the smallest possible softening.',
        basePrice: 200,
        image: IMG.macchiato,
        calories: 25,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'whole milk foam'],
        allergens: ['Milk'],
        tags: ['coffee', 'espresso', 'hot', 'macchiato', 'strong'],
        rating: 4.5,
        ratingCount: 96,
        orderCount: 640,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Spanish Latte',
        slug: 'spanish-latte',
        description: 'Slow-cooked condensed milk, espresso and steamed milk. Sweet, but not cloying.',
        basePrice: 260,
        image: IMG.spanishLatte,
        calories: 320,
        prepTimeMinutes: 6,
        ingredients: ['house espresso blend', 'condensed milk', 'whole milk'],
        allergens: ['Milk'],
        tags: ['coffee', 'milk', 'sweet', 'hot', 'spanish latte'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 412,
        orderCount: 2410,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Caramel Latte',
        slug: 'caramel-latte',
        description: 'Latte with a salted caramel we cook in-house every second morning.',
        basePrice: 250,
        image: IMG.caramelLatte,
        calories: 300,
        prepTimeMinutes: 6,
        ingredients: ['house espresso blend', 'whole milk', 'salted caramel'],
        allergens: ['Milk'],
        tags: ['coffee', 'caramel', 'sweet', 'hot', 'latte'],
        rating: 4.6,
        ratingCount: 224,
        orderCount: 1480,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Vanilla Latte',
        slug: 'vanilla-latte',
        description: 'Scraped Coorg vanilla bean steeped into the milk before it meets the shot.',
        basePrice: 250,
        image: IMG.vanillaLatte,
        calories: 280,
        prepTimeMinutes: 6,
        ingredients: ['house espresso blend', 'whole milk', 'Coorg vanilla'],
        allergens: ['Milk'],
        tags: ['coffee', 'vanilla', 'sweet', 'hot', 'latte'],
        rating: 4.5,
        ratingCount: 198,
        orderCount: 1340,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Hazelnut Latte',
        slug: 'hazelnut-latte',
        description: 'Roasted hazelnut praline stirred through a double-shot latte.',
        basePrice: 250,
        image: IMG.hazelnutLatte,
        calories: 310,
        prepTimeMinutes: 6,
        ingredients: ['house espresso blend', 'whole milk', 'hazelnut praline'],
        allergens: ['Milk', 'Tree nuts'],
        nuts: true,
        tags: ['coffee', 'hazelnut', 'nutty', 'hot', 'latte'],
        rating: 4.6,
        ratingCount: 176,
        orderCount: 1180,
        modifiers: COFFEE_MODS,
      },
    ],
  },

  // ─────────────────────────────────────────────────────── Cold Coffee
  {
    name: 'Cold Coffee',
    slug: 'cold-coffee',
    description: 'Built over slow-melting ice, or steeped for eighteen hours. Never watery.',
    image: IMG.coldBrew,
    products: [
      {
        name: 'Iced Americano',
        slug: 'iced-americano',
        description: 'Espresso poured over cold filtered water and a single large cube.',
        basePrice: 210,
        image: IMG.icedAmericano,
        calories: 15,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'filtered water', 'ice'],
        tags: ['coffee', 'cold', 'iced', 'black', 'refreshing'],
        vegan: true,
        rating: 4.5,
        ratingCount: 186,
        orderCount: 1420,
        modifiers: ['size', 'sweetness', 'iceLevel', 'coffeeAddons'],
      },
      {
        name: 'Iced Latte',
        slug: 'iced-latte',
        description: 'Cold milk, a double shot, and enough ice to keep it honest through a long lunch.',
        basePrice: 240,
        image: IMG.icedLatte,
        calories: 180,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'cold whole milk', 'ice'],
        allergens: ['Milk'],
        tags: ['coffee', 'cold', 'iced', 'milk', 'latte'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 348,
        orderCount: 2560,
        modifiers: COLD_MODS,
      },
      {
        name: 'Iced Mocha',
        slug: 'iced-mocha',
        description: 'Dark chocolate ganache shaken cold with espresso, then topped with milk.',
        basePrice: 280,
        image: IMG.icedMocha,
        calories: 310,
        prepTimeMinutes: 5,
        ingredients: ['house espresso blend', 'cold milk', 'dark chocolate ganache', 'ice'],
        allergens: ['Milk'],
        tags: ['coffee', 'cold', 'chocolate', 'iced', 'sweet'],
        rating: 4.6,
        ratingCount: 212,
        orderCount: 1520,
        modifiers: COLD_MODS,
      },
      {
        name: 'Cold Brew',
        slug: 'cold-brew',
        description: 'Eighteen hours in cold water. Low acid, syrupy, tasting of plum and cane sugar.',
        story:
          'We steep coarse-ground Kalledevarapura naturals overnight in a stainless tower, then rest the concentrate a further day before service.',
        basePrice: 240,
        image: IMG.coldBrew,
        calories: 10,
        prepTimeMinutes: 3,
        ingredients: ['single-origin naturals', 'filtered water', 'ice'],
        tags: ['coffee', 'cold', 'cold brew', 'black', 'smooth'],
        vegan: true,
        bestseller: true,
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 392,
        orderCount: 2310,
        modifiers: ['size', 'sweetness', 'iceLevel', 'coffeeAddons'],
      },
      {
        name: 'Vanilla Cold Brew',
        slug: 'vanilla-cold-brew',
        description: 'Our cold brew with vanilla cream floated on top, left for you to stir in.',
        basePrice: 270,
        image: IMG.vanillaColdBrew,
        calories: 190,
        prepTimeMinutes: 4,
        ingredients: ['cold brew concentrate', 'vanilla cream', 'Coorg vanilla', 'ice'],
        allergens: ['Milk'],
        tags: ['coffee', 'cold', 'cold brew', 'vanilla', 'sweet'],
        rating: 4.7,
        ratingCount: 246,
        orderCount: 1680,
        modifiers: ['size', 'sweetness', 'iceLevel', 'coffeeAddons'],
      },
      {
        name: 'Coffee Tonic',
        slug: 'coffee-tonic',
        description: 'Cold brew over Indian tonic and a wide strip of orange peel. Bitter, bright, alive.',
        basePrice: 280,
        image: IMG.coffeeTonic,
        calories: 90,
        prepTimeMinutes: 4,
        ingredients: ['cold brew concentrate', 'tonic water', 'orange peel', 'ice'],
        tags: ['coffee', 'cold', 'tonic', 'citrus', 'refreshing'],
        vegan: true,
        isNew: true,
        rating: 4.6,
        ratingCount: 118,
        orderCount: 720,
        modifiers: ['size', 'iceLevel', 'coffeeAddons'],
      },
      {
        name: 'Espresso Tonic',
        slug: 'espresso-tonic',
        description: 'A fresh double shot dropped through tonic — drink it in the first two minutes.',
        basePrice: 280,
        image: IMG.espressoTonic,
        calories: 85,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'tonic water', 'lime', 'ice'],
        tags: ['coffee', 'cold', 'tonic', 'sparkling', 'refreshing'],
        vegan: true,
        isNew: true,
        rating: 4.7,
        ratingCount: 134,
        orderCount: 840,
        modifiers: ['size', 'iceLevel', 'coffeeAddons'],
      },
      {
        name: 'Affogato',
        slug: 'affogato',
        description: 'A hot double shot poured over Madagascar vanilla gelato at the table.',
        basePrice: 290,
        image: IMG.affogato,
        calories: 240,
        prepTimeMinutes: 4,
        ingredients: ['house espresso blend', 'vanilla bean gelato'],
        allergens: ['Milk'],
        tags: ['coffee', 'dessert', 'gelato', 'affogato', 'sweet'],
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 208,
        orderCount: 1140,
        modifiers: ['dessertAddons'],
      },
    ],
  },

  // ────────────────────────────────────────────────────── Matcha & Tea
  {
    name: 'Matcha & Tea',
    slug: 'matcha-tea',
    description: 'Ceremonial-grade matcha whisked to order, and leaf tea brewed by the timer.',
    image: IMG.matchaLatte,
    products: [
      {
        name: 'Matcha Latte',
        slug: 'matcha-latte',
        description: 'Uji ceremonial matcha whisked smooth, then lengthened with warm milk.',
        basePrice: 280,
        image: IMG.matchaLatte,
        calories: 190,
        prepTimeMinutes: 6,
        ingredients: ['Uji ceremonial matcha', 'whole milk'],
        allergens: ['Milk'],
        tags: ['matcha', 'green tea', 'hot', 'milk', 'earthy'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 296,
        orderCount: 1920,
        modifiers: ['size', 'milk', 'sweetness', 'matchaAddons'],
      },
      {
        name: 'Iced Matcha',
        slug: 'iced-matcha',
        description: 'Cold-whisked matcha layered over milk and ice, unsweetened unless you say so.',
        basePrice: 290,
        image: IMG.icedMatcha,
        calories: 180,
        prepTimeMinutes: 5,
        ingredients: ['Uji ceremonial matcha', 'cold milk', 'ice'],
        allergens: ['Milk'],
        tags: ['matcha', 'cold', 'iced', 'green tea', 'refreshing'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 312,
        orderCount: 2040,
        modifiers: ['size', 'milk', 'sweetness', 'iceLevel', 'matchaAddons'],
      },
      {
        name: 'Ceremonial Matcha',
        slug: 'ceremonial-matcha',
        description: 'Usucha, whisked in a chawan with 70°C water. No milk, no sugar, no hurry.',
        story: 'Single-cultivar Okumidori from a family plot in Uji, stone-milled and shipped in 20g tins.',
        basePrice: 340,
        image: IMG.ceremonialMatcha,
        calories: 5,
        prepTimeMinutes: 7,
        ingredients: ['single-cultivar Okumidori matcha', 'filtered water'],
        tags: ['matcha', 'ceremonial', 'hot', 'pure', 'earthy'],
        vegan: true,
        chefSpecial: true,
        rating: 4.9,
        ratingCount: 88,
        orderCount: 410,
        modifiers: ['sweetness'],
      },
      {
        name: 'Masala Chai',
        slug: 'masala-chai',
        description: 'Assam leaf boiled with ginger, green cardamom and a little black pepper.',
        story: 'Our masala is ground weekly — cardamom-forward, closer to a Bombay cutting chai than a spice bomb.',
        basePrice: 160,
        image: IMG.masalaChai,
        calories: 140,
        prepTimeMinutes: 7,
        ingredients: ['Assam black tea', 'ginger', 'green cardamom', 'black pepper', 'whole milk'],
        allergens: ['Milk'],
        tags: ['tea', 'chai', 'hot', 'spiced', 'masala'],
        spicy: true,
        bestseller: true,
        rating: 4.8,
        ratingCount: 428,
        orderCount: 2870,
        modifiers: ['size', 'milk', 'sweetness', 'teaStrength'],
      },
      {
        name: 'Earl Grey',
        slug: 'earl-grey',
        description: 'Nilgiri black leaf scented with Calabrian bergamot. Brewed four minutes.',
        basePrice: 170,
        image: IMG.earlGrey,
        calories: 5,
        prepTimeMinutes: 6,
        ingredients: ['Nilgiri black tea', 'bergamot'],
        tags: ['tea', 'black tea', 'hot', 'bergamot', 'earl grey'],
        vegan: true,
        rating: 4.4,
        ratingCount: 96,
        orderCount: 560,
        modifiers: ['size', 'sweetness', 'teaStrength'],
      },
      {
        name: 'Chamomile Tea',
        slug: 'chamomile-tea',
        description: 'Whole Egyptian chamomile flowers. Gentle, honeyed, caffeine-free.',
        basePrice: 170,
        image: IMG.chamomile,
        calories: 5,
        prepTimeMinutes: 6,
        ingredients: ['Egyptian chamomile flowers'],
        tags: ['tea', 'herbal', 'hot', 'caffeine free', 'chamomile'],
        vegan: true,
        rating: 4.5,
        ratingCount: 84,
        orderCount: 490,
        modifiers: ['size', 'sweetness', 'teaStrength'],
      },
      {
        name: 'Green Tea',
        slug: 'green-tea',
        description: 'First-flush Darjeeling green, brewed at 75°C so it never turns bitter.',
        basePrice: 160,
        image: IMG.greenTea,
        calories: 5,
        prepTimeMinutes: 5,
        ingredients: ['first-flush Darjeeling green tea'],
        tags: ['tea', 'green tea', 'hot', 'light', 'darjeeling'],
        vegan: true,
        rating: 4.3,
        ratingCount: 72,
        orderCount: 520,
        modifiers: ['size', 'sweetness', 'teaStrength'],
      },
      {
        name: 'Moroccan Mint Tea',
        slug: 'moroccan-mint-tea',
        description: 'Gunpowder green with a bunch of spearmint, poured high from the pot.',
        basePrice: 190,
        image: IMG.mintTea,
        calories: 30,
        prepTimeMinutes: 7,
        ingredients: ['gunpowder green tea', 'spearmint', 'cane sugar'],
        tags: ['tea', 'mint', 'hot', 'moroccan', 'refreshing'],
        vegan: true,
        rating: 4.6,
        ratingCount: 108,
        orderCount: 620,
        modifiers: ['size', 'sweetness', 'teaStrength'],
      },
    ],
  },

  // ───────────────────────────────────────────────────────── Breakfast
  {
    name: 'Breakfast',
    slug: 'breakfast',
    description: 'Served from open until four, because mornings should be allowed to run late.',
    image: IMG.avocadoToast,
    products: [
      {
        name: 'Avocado Toast',
        slug: 'avocado-toast',
        description: 'Crushed avocado on grilled sourdough with lemon, chilli and toasted dukkah.',
        basePrice: 390,
        image: IMG.avocadoToast,
        calories: 420,
        prepTimeMinutes: 12,
        ingredients: ['avocado', 'sourdough', 'lemon', 'red chilli', 'dukkah', 'olive oil'],
        allergens: ['Gluten', 'Sesame', 'Tree nuts'],
        gluten: true,
        nuts: true,
        tags: ['breakfast', 'toast', 'avocado', 'healthy', 'vegetarian'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 384,
        orderCount: 2180,
        modifiers: ['bread', 'toastAddons'],
      },
      {
        name: 'Eggs Benedict',
        slug: 'eggs-benedict',
        description: 'Two poached eggs on a toasted muffin with hollandaise and wilted spinach.',
        basePrice: 450,
        image: IMG.eggsBenedict,
        calories: 610,
        prepTimeMinutes: 16,
        ingredients: ['free-range eggs', 'English muffin', 'hollandaise', 'spinach', 'butter'],
        allergens: ['Egg', 'Gluten', 'Milk'],
        egg: true,
        gluten: true,
        tags: ['breakfast', 'eggs', 'benedict', 'brunch', 'hollandaise'],
        bestseller: true,
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 296,
        orderCount: 1640,
        modifiers: ['eggStyle', 'toastAddons'],
      },
      {
        name: 'Scrambled Eggs & Sourdough',
        slug: 'scrambled-eggs-sourdough',
        description: 'Soft-scrambled free-range eggs, cultured butter, chives, thick-cut sourdough.',
        basePrice: 390,
        image: IMG.scrambledEggs,
        calories: 480,
        prepTimeMinutes: 12,
        ingredients: ['free-range eggs', 'cultured butter', 'chives', 'sourdough'],
        allergens: ['Egg', 'Gluten', 'Milk'],
        egg: true,
        gluten: true,
        tags: ['breakfast', 'eggs', 'scrambled', 'sourdough', 'simple'],
        rating: 4.6,
        ratingCount: 214,
        orderCount: 1380,
        modifiers: ['bread', 'toastAddons'],
      },
      {
        name: 'French Toast',
        slug: 'french-toast',
        description: 'Thick brioche soaked overnight, griddled in butter, with maple and mascarpone.',
        basePrice: 410,
        image: IMG.frenchToast,
        calories: 640,
        prepTimeMinutes: 14,
        ingredients: ['brioche', 'free-range eggs', 'maple syrup', 'mascarpone', 'cinnamon'],
        allergens: ['Egg', 'Gluten', 'Milk'],
        egg: true,
        gluten: true,
        tags: ['breakfast', 'sweet', 'french toast', 'brioche', 'maple'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 332,
        orderCount: 1820,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Granola & Greek Yogurt',
        slug: 'granola-greek-yogurt',
        description: 'House-baked oat and almond granola, thick yogurt, seasonal fruit, wild honey.',
        basePrice: 340,
        image: IMG.granola,
        calories: 390,
        prepTimeMinutes: 8,
        ingredients: ['rolled oats', 'almonds', 'Greek yogurt', 'seasonal fruit', 'wild honey'],
        allergens: ['Milk', 'Tree nuts', 'Gluten'],
        nuts: true,
        gluten: true,
        tags: ['breakfast', 'granola', 'yogurt', 'healthy', 'light'],
        rating: 4.5,
        ratingCount: 178,
        orderCount: 1120,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Açaí Bowl',
        slug: 'acai-bowl',
        description: 'Frozen açaí and banana blended thick, with granola, coconut and fresh berries.',
        basePrice: 420,
        image: IMG.acaiBowl,
        calories: 410,
        prepTimeMinutes: 10,
        ingredients: ['açaí', 'banana', 'granola', 'coconut flakes', 'berries'],
        allergens: ['Tree nuts', 'Gluten'],
        nuts: true,
        gluten: true,
        vegan: true,
        tags: ['breakfast', 'acai', 'bowl', 'vegan', 'healthy'],
        isNew: true,
        rating: 4.6,
        ratingCount: 142,
        orderCount: 880,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Breakfast Croissant',
        slug: 'breakfast-croissant',
        description: 'Our croissant split and filled with folded egg, aged cheddar and tomato jam.',
        basePrice: 360,
        image: IMG.breakfastCroissant,
        calories: 520,
        prepTimeMinutes: 11,
        ingredients: ['butter croissant', 'free-range eggs', 'aged cheddar', 'tomato jam'],
        allergens: ['Egg', 'Gluten', 'Milk'],
        egg: true,
        gluten: true,
        tags: ['breakfast', 'croissant', 'eggs', 'cheese', 'sandwich'],
        rating: 4.6,
        ratingCount: 196,
        orderCount: 1240,
        modifiers: ['sandwichAddons'],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────── Bakery
  {
    name: 'Bakery',
    slug: 'bakery',
    description: 'Laminated at midnight, baked at six. What sells out, sells out.',
    image: IMG.butterCroissant,
    products: [
      {
        name: 'Butter Croissant',
        slug: 'butter-croissant',
        description: 'Seventy-two hour ferment, French cultured butter, twenty-seven layers.',
        basePrice: 180,
        image: IMG.butterCroissant,
        calories: 310,
        prepTimeMinutes: 3,
        ingredients: ['wheat flour', 'French cultured butter', 'milk', 'sea salt'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        tags: ['bakery', 'croissant', 'butter', 'pastry', 'flaky'],
        bestseller: true,
        rating: 4.9,
        ratingCount: 468,
        orderCount: 3120,
        modifiers: [],
      },
      {
        name: 'Almond Croissant',
        slug: 'almond-croissant',
        description: 'Yesterday’s croissant, filled with frangipane and baked again until dark.',
        basePrice: 220,
        image: IMG.pastryCase,
        calories: 430,
        prepTimeMinutes: 4,
        ingredients: ['croissant', 'almond frangipane', 'flaked almonds', 'icing sugar'],
        allergens: ['Gluten', 'Milk', 'Tree nuts', 'Egg'],
        gluten: true,
        nuts: true,
        egg: true,
        tags: ['bakery', 'croissant', 'almond', 'pastry', 'sweet'],
        rating: 4.7,
        ratingCount: 224,
        orderCount: 1460,
        modifiers: [],
      },
      {
        name: 'Pain au Chocolat',
        slug: 'pain-au-chocolat',
        description: 'Two batons of 62% Valrhona rolled into the same dough as our croissant.',
        basePrice: 210,
        image: IMG.bread,
        calories: 400,
        prepTimeMinutes: 3,
        ingredients: ['wheat flour', 'cultured butter', '62% dark chocolate'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        tags: ['bakery', 'chocolate', 'pastry', 'croissant', 'sweet'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 286,
        orderCount: 1880,
        modifiers: [],
      },
      {
        name: 'Cinnamon Roll',
        slug: 'cinnamon-roll',
        description: 'Soft enriched dough, Ceylon cinnamon, cream cheese glaze poured warm.',
        basePrice: 230,
        image: IMG.cinnamonRoll,
        calories: 480,
        prepTimeMinutes: 4,
        ingredients: ['enriched dough', 'Ceylon cinnamon', 'brown sugar', 'cream cheese'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['bakery', 'cinnamon', 'roll', 'sweet', 'warm'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 342,
        orderCount: 2060,
        modifiers: [],
      },
      {
        name: 'Blueberry Muffin',
        slug: 'blueberry-muffin',
        description: 'Buttermilk crumb, folded through with whole blueberries and lemon zest.',
        basePrice: 190,
        image: IMG.muffin,
        calories: 380,
        prepTimeMinutes: 3,
        ingredients: ['wheat flour', 'buttermilk', 'blueberries', 'lemon zest'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['bakery', 'muffin', 'blueberry', 'sweet', 'breakfast'],
        rating: 4.4,
        ratingCount: 148,
        orderCount: 940,
        modifiers: [],
      },
      {
        name: 'Banana Bread',
        slug: 'banana-bread',
        description: 'Very ripe bananas, brown butter, walnuts. Toasted and buttered on request.',
        basePrice: 180,
        image: IMG.bananaBread,
        calories: 360,
        prepTimeMinutes: 4,
        ingredients: ['bananas', 'brown butter', 'walnuts', 'wheat flour'],
        allergens: ['Gluten', 'Milk', 'Egg', 'Tree nuts'],
        gluten: true,
        egg: true,
        nuts: true,
        tags: ['bakery', 'banana', 'bread', 'walnut', 'sweet'],
        rating: 4.6,
        ratingCount: 186,
        orderCount: 1080,
        modifiers: [],
      },
      {
        name: 'Chocolate Chip Cookie',
        slug: 'chocolate-chip-cookie',
        description: 'Brown-butter dough rested three days, sea salt on top, deliberately underbaked.',
        basePrice: 150,
        image: IMG.cookie,
        calories: 290,
        prepTimeMinutes: 3,
        ingredients: ['brown butter', 'dark chocolate', 'wheat flour', 'sea salt'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['bakery', 'cookie', 'chocolate', 'sweet', 'snack'],
        bestseller: true,
        rating: 4.9,
        ratingCount: 412,
        orderCount: 2740,
        modifiers: [],
      },
    ],
  },

  // ──────────────────────────────────────────────────────── Sandwiches
  {
    name: 'Sandwiches',
    slug: 'sandwiches',
    description: 'Pressed on house sourdough or ciabatta, cut on the diagonal, always.',
    image: IMG.pestoPanini,
    products: [
      {
        name: 'Chicken Pesto Panini',
        slug: 'chicken-pesto-panini',
        description: 'Grilled chicken, basil pesto, provolone and roast tomato on pressed ciabatta.',
        basePrice: 420,
        image: IMG.pestoPanini,
        calories: 640,
        prepTimeMinutes: 14,
        ingredients: ['chicken breast', 'basil pesto', 'provolone', 'roast tomato', 'ciabatta'],
        allergens: ['Gluten', 'Milk', 'Tree nuts'],
        nonVeg: true,
        gluten: true,
        nuts: true,
        tags: ['sandwich', 'panini', 'chicken', 'pesto', 'grilled'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 312,
        orderCount: 1940,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Grilled Cheese',
        slug: 'grilled-cheese',
        description: 'Three cheeses — cheddar, gruyère, mozzarella — on buttered sourdough.',
        basePrice: 340,
        image: IMG.grilledCheese,
        calories: 590,
        prepTimeMinutes: 11,
        ingredients: ['aged cheddar', 'gruyère', 'mozzarella', 'sourdough', 'butter'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        tags: ['sandwich', 'cheese', 'grilled', 'comfort', 'vegetarian'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 268,
        orderCount: 1720,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Smoked Chicken Sandwich',
        slug: 'smoked-chicken-sandwich',
        description: 'House-smoked chicken, pickled onion, gem lettuce and mustard mayonnaise.',
        basePrice: 440,
        image: IMG.sandwich,
        calories: 610,
        prepTimeMinutes: 13,
        ingredients: ['smoked chicken', 'pickled onion', 'gem lettuce', 'mustard mayonnaise', 'sourdough'],
        allergens: ['Gluten', 'Egg', 'Mustard'],
        nonVeg: true,
        gluten: true,
        egg: true,
        tags: ['sandwich', 'chicken', 'smoked', 'lunch'],
        rating: 4.6,
        ratingCount: 204,
        orderCount: 1280,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Burrata & Tomato Sandwich',
        slug: 'burrata-tomato-sandwich',
        description: 'Torn burrata, heirloom tomato, basil oil and aged balsamic on focaccia.',
        basePrice: 460,
        image: IMG.burrataSandwich,
        calories: 570,
        prepTimeMinutes: 12,
        ingredients: ['burrata', 'heirloom tomato', 'basil oil', 'aged balsamic', 'focaccia'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        tags: ['sandwich', 'burrata', 'tomato', 'italian', 'vegetarian'],
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 186,
        orderCount: 1060,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Mushroom Melt',
        slug: 'mushroom-melt',
        description: 'Butter-roasted mushrooms, thyme, caramelised onion and melted gruyère.',
        basePrice: 380,
        image: IMG.mushroomMelt,
        calories: 540,
        prepTimeMinutes: 13,
        ingredients: ['button mushrooms', 'oyster mushrooms', 'thyme', 'caramelised onion', 'gruyère'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        tags: ['sandwich', 'mushroom', 'cheese', 'melt', 'vegetarian'],
        rating: 4.6,
        ratingCount: 164,
        orderCount: 980,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Avocado & Feta Toast',
        slug: 'avocado-feta-toast',
        description: 'Avocado and Greek feta on multigrain, with mint, pomegranate and olive oil.',
        basePrice: 400,
        image: IMG.avocadoToast,
        calories: 460,
        prepTimeMinutes: 11,
        ingredients: ['avocado', 'Greek feta', 'mint', 'pomegranate', 'multigrain bread'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        tags: ['sandwich', 'toast', 'avocado', 'feta', 'vegetarian'],
        rating: 4.6,
        ratingCount: 172,
        orderCount: 1020,
        modifiers: ['bread', 'toastAddons'],
      },
    ],
  },

  // ───────────────────────────────────────────────────────────── Pasta
  {
    name: 'Pasta',
    slug: 'pasta',
    description: 'Rolled and cut each morning. Sauced to order, finished off the heat.',
    image: IMG.trufflePasta,
    products: [
      {
        name: 'Truffle Mushroom Pasta',
        slug: 'truffle-mushroom-pasta',
        description: 'Creamy wild mushroom tagliatelle finished with parmesan and black truffle oil.',
        story:
          'Three mushrooms — button, oyster and dried porcini — built into a sauce with the porcini soaking liquor, then loosened with pasta water rather than more cream.',
        basePrice: 495,
        image: IMG.trufflePasta,
        calories: 720,
        prepTimeMinutes: 18,
        ingredients: ['tagliatelle', 'wild mushrooms', 'porcini', 'cream', 'parmesan', 'black truffle oil'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['pasta', 'truffle', 'mushroom', 'creamy', 'signature'],
        bestseller: true,
        chefSpecial: true,
        rating: 4.9,
        ratingCount: 428,
        orderCount: 2280,
        modifiers: ['pastaAddons', 'pastaSpice'],
      },
      {
        name: 'Creamy Pesto Pasta',
        slug: 'creamy-pesto-pasta',
        description: 'Basil and pine nut pesto loosened with cream, tossed through fusilli.',
        basePrice: 450,
        image: IMG.pestoPasta,
        calories: 680,
        prepTimeMinutes: 16,
        ingredients: ['fusilli', 'basil', 'pine nuts', 'parmesan', 'cream', 'garlic'],
        allergens: ['Gluten', 'Milk', 'Tree nuts'],
        gluten: true,
        nuts: true,
        tags: ['pasta', 'pesto', 'basil', 'creamy', 'vegetarian'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 296,
        orderCount: 1740,
        modifiers: ['pastaAddons', 'pastaSpice'],
      },
      {
        name: 'Arrabbiata',
        slug: 'arrabbiata',
        description: 'Slow San Marzano sauce with garlic and dried chilli. Properly hot.',
        basePrice: 420,
        image: IMG.arrabbiata,
        calories: 560,
        prepTimeMinutes: 15,
        ingredients: ['penne', 'San Marzano tomatoes', 'garlic', 'dried chilli', 'basil', 'olive oil'],
        allergens: ['Gluten'],
        gluten: true,
        spicy: true,
        vegan: true,
        tags: ['pasta', 'arrabbiata', 'tomato', 'spicy', 'vegan'],
        rating: 4.5,
        ratingCount: 198,
        orderCount: 1180,
        modifiers: ['pastaAddons', 'pastaSpice'],
      },
      {
        name: 'Alfredo',
        slug: 'alfredo',
        description: 'Parmesan and butter emulsified into a silk sauce over fettuccine. Nothing else.',
        basePrice: 460,
        image: IMG.alfredo,
        calories: 740,
        prepTimeMinutes: 16,
        ingredients: ['fettuccine', 'parmesan', 'butter', 'black pepper'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['pasta', 'alfredo', 'creamy', 'cheese', 'vegetarian'],
        rating: 4.6,
        ratingCount: 214,
        orderCount: 1320,
        modifiers: ['pastaAddons', 'pastaSpice'],
      },
      {
        name: 'Chicken Alfredo',
        slug: 'chicken-alfredo',
        description: 'Our alfredo with a grilled, rested chicken breast sliced over the top.',
        basePrice: 540,
        image: IMG.pasta,
        calories: 890,
        prepTimeMinutes: 19,
        ingredients: ['fettuccine', 'chicken breast', 'parmesan', 'butter', 'black pepper'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        nonVeg: true,
        gluten: true,
        egg: true,
        tags: ['pasta', 'chicken', 'alfredo', 'creamy', 'protein'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 262,
        orderCount: 1560,
        modifiers: ['pastaAddons', 'pastaSpice'],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────── Salads
  {
    name: 'Salads',
    slug: 'salads',
    description: 'Dressed at the last second, so nothing arrives tired.',
    image: IMG.caesarSalad,
    products: [
      {
        name: 'Caesar Salad',
        slug: 'caesar-salad',
        description: 'Gem lettuce, anchovy dressing, sourdough croutons and shaved parmesan.',
        basePrice: 390,
        image: IMG.caesarSalad,
        calories: 420,
        prepTimeMinutes: 10,
        ingredients: ['gem lettuce', 'anchovy', 'parmesan', 'sourdough croutons', 'egg yolk'],
        allergens: ['Fish', 'Egg', 'Gluten', 'Milk'],
        nonVeg: true,
        egg: true,
        gluten: true,
        tags: ['salad', 'caesar', 'parmesan', 'classic', 'lunch'],
        bestseller: true,
        rating: 4.6,
        ratingCount: 246,
        orderCount: 1480,
        modifiers: ['saladDressing', 'saladAddons'],
      },
      {
        name: 'Burrata Salad',
        slug: 'burrata-salad',
        description: 'A whole burrata with heirloom tomatoes, basil, and peach when it’s in season.',
        basePrice: 520,
        image: IMG.saladBowl,
        calories: 480,
        prepTimeMinutes: 9,
        ingredients: ['burrata', 'heirloom tomatoes', 'basil', 'aged balsamic', 'olive oil'],
        allergens: ['Milk'],
        tags: ['salad', 'burrata', 'tomato', 'italian', 'vegetarian'],
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 208,
        orderCount: 1140,
        modifiers: ['saladDressing', 'saladAddons'],
      },
      {
        name: 'Quinoa Salad',
        slug: 'quinoa-salad',
        description: 'Tricolour quinoa with roast pumpkin, kale, cranberry and toasted seeds.',
        basePrice: 430,
        image: IMG.quinoaSalad,
        calories: 440,
        prepTimeMinutes: 10,
        ingredients: ['tricolour quinoa', 'roast pumpkin', 'kale', 'cranberry', 'pumpkin seeds'],
        vegan: true,
        tags: ['salad', 'quinoa', 'vegan', 'healthy', 'grain bowl'],
        rating: 4.5,
        ratingCount: 164,
        orderCount: 920,
        modifiers: ['saladDressing', 'saladAddons'],
      },
      {
        name: 'Mediterranean Salad',
        slug: 'mediterranean-salad',
        description: 'Cucumber, olive, feta, red onion and oregano with lemon and olive oil.',
        basePrice: 410,
        image: IMG.mediterraneanSalad,
        calories: 380,
        prepTimeMinutes: 9,
        ingredients: ['cucumber', 'Kalamata olives', 'feta', 'red onion', 'oregano', 'lemon'],
        allergens: ['Milk'],
        tags: ['salad', 'mediterranean', 'feta', 'olive', 'vegetarian'],
        rating: 4.5,
        ratingCount: 142,
        orderCount: 860,
        modifiers: ['saladDressing', 'saladAddons'],
      },
    ],
  },

  // ────────────────────────────────────────────────────────── Desserts
  {
    name: 'Desserts',
    slug: 'desserts',
    description: 'Made in small trays each morning, and finished by evening.',
    image: IMG.tiramisu,
    products: [
      {
        name: 'Tiramisu',
        slug: 'tiramisu',
        description: 'Savoiardi soaked in our own espresso, mascarpone cream, bitter cocoa.',
        basePrice: 340,
        image: IMG.tiramisu,
        calories: 460,
        prepTimeMinutes: 5,
        ingredients: ['savoiardi', 'mascarpone', 'espresso', 'cocoa', 'egg yolk'],
        allergens: ['Egg', 'Gluten', 'Milk'],
        egg: true,
        gluten: true,
        tags: ['dessert', 'tiramisu', 'coffee', 'italian', 'sweet'],
        bestseller: true,
        rating: 4.9,
        ratingCount: 386,
        orderCount: 2140,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Basque Cheesecake',
        slug: 'basque-cheesecake',
        description: 'Burnt on top, barely set in the middle. Baked hot and fast, served at room temperature.',
        basePrice: 320,
        image: IMG.basqueCheesecake,
        calories: 490,
        prepTimeMinutes: 5,
        ingredients: ['cream cheese', 'cream', 'free-range eggs', 'vanilla'],
        allergens: ['Egg', 'Milk'],
        egg: true,
        tags: ['dessert', 'cheesecake', 'basque', 'burnt', 'sweet'],
        bestseller: true,
        chefSpecial: true,
        rating: 4.9,
        ratingCount: 412,
        orderCount: 2320,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Chocolate Tart',
        slug: 'chocolate-tart',
        description: '70% ganache in a cocoa shell, with olive oil and flaked salt.',
        basePrice: 330,
        image: IMG.chocolateTart,
        calories: 520,
        prepTimeMinutes: 5,
        ingredients: ['70% dark chocolate', 'cream', 'cocoa pastry', 'olive oil', 'sea salt'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['dessert', 'chocolate', 'tart', 'rich', 'sweet'],
        rating: 4.8,
        ratingCount: 268,
        orderCount: 1480,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Chocolate Brownie',
        slug: 'chocolate-brownie',
        description: 'Dense, fudgy, walnut-studded. Warmed through if you’re eating in.',
        basePrice: 280,
        image: IMG.brownie,
        calories: 440,
        prepTimeMinutes: 5,
        ingredients: ['dark chocolate', 'walnuts', 'butter', 'free-range eggs'],
        allergens: ['Gluten', 'Milk', 'Egg', 'Tree nuts'],
        gluten: true,
        egg: true,
        nuts: true,
        tags: ['dessert', 'brownie', 'chocolate', 'walnut', 'warm'],
        bestseller: true,
        rating: 4.7,
        ratingCount: 324,
        orderCount: 1920,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Panna Cotta',
        slug: 'panna-cotta',
        description: 'Barely-set vanilla cream with a sharp seasonal fruit compote.',
        basePrice: 310,
        image: IMG.pannaCotta,
        calories: 340,
        prepTimeMinutes: 5,
        ingredients: ['cream', 'Coorg vanilla', 'seasonal fruit compote'],
        allergens: ['Milk'],
        tags: ['dessert', 'panna cotta', 'vanilla', 'light', 'italian'],
        rating: 4.6,
        ratingCount: 156,
        orderCount: 880,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Lemon Tart',
        slug: 'lemon-tart',
        description: 'Sharp lemon curd in a thin sweet shell, brûléed to order.',
        basePrice: 300,
        image: IMG.lemonTart,
        calories: 390,
        prepTimeMinutes: 6,
        ingredients: ['lemon curd', 'sweet pastry', 'free-range eggs', 'butter'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        gluten: true,
        egg: true,
        tags: ['dessert', 'lemon', 'tart', 'citrus', 'sharp'],
        rating: 4.7,
        ratingCount: 148,
        orderCount: 810,
        modifiers: ['dessertAddons'],
      },
      {
        name: 'Affogato Sundae',
        slug: 'affogato-sundae',
        description: 'Vanilla gelato, a hot double shot, brownie rubble and toasted hazelnut.',
        basePrice: 320,
        image: IMG.dessertPlate,
        calories: 470,
        prepTimeMinutes: 6,
        ingredients: ['vanilla gelato', 'espresso', 'brownie', 'hazelnuts'],
        allergens: ['Milk', 'Gluten', 'Egg', 'Tree nuts'],
        gluten: true,
        egg: true,
        nuts: true,
        tags: ['dessert', 'affogato', 'gelato', 'coffee', 'sundae'],
        isNew: true,
        rating: 4.8,
        ratingCount: 112,
        orderCount: 540,
        modifiers: ['dessertAddons'],
      },
    ],
  },

  // ─────────────────────────────────────────────── Signature Specials
  {
    name: 'Signature Specials',
    slug: 'signature',
    description: 'The drinks and plates you can only get from us — several of them seasonal.',
    image: IMG.filterCoffee,
    products: [
      {
        name: 'Alaap Filter Coffee',
        slug: 'alaap-filter-coffee',
        description: 'South Indian filter decoction pulled long, with jaggery-sweetened boiled milk.',
        story:
          'Made in a traditional stainless filter with a 70:30 coffee-to-chicory ratio, then finished with jaggery instead of white sugar. Served in a davara set.',
        basePrice: 240,
        image: IMG.filterCoffee,
        calories: 180,
        prepTimeMinutes: 8,
        ingredients: ['filter coffee decoction', 'chicory', 'whole milk', 'jaggery'],
        allergens: ['Milk'],
        tags: ['coffee', 'filter coffee', 'signature', 'indian', 'jaggery'],
        bestseller: true,
        chefSpecial: true,
        rating: 4.9,
        ratingCount: 348,
        orderCount: 2210,
        modifiers: ['size', 'sweetness'],
      },
      {
        name: 'Rose Cardamom Latte',
        slug: 'rose-cardamom-latte',
        description: 'Kannauj rose, green cardamom and espresso. Floral without tipping into perfume.',
        basePrice: 280,
        image: IMG.spanishLatte,
        calories: 260,
        prepTimeMinutes: 7,
        ingredients: ['house espresso blend', 'whole milk', 'Kannauj rose', 'green cardamom'],
        allergens: ['Milk'],
        tags: ['coffee', 'rose', 'cardamom', 'signature', 'floral', 'seasonal'],
        seasonal: true,
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 216,
        orderCount: 1180,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Pistachio Latte',
        slug: 'pistachio-latte',
        description: 'Ground Iranian pistachio paste, espresso and milk, with a salted pistachio crumb.',
        basePrice: 300,
        image: IMG.hazelnutLatte,
        calories: 340,
        prepTimeMinutes: 7,
        ingredients: ['house espresso blend', 'whole milk', 'Iranian pistachio paste', 'sea salt'],
        allergens: ['Milk', 'Tree nuts'],
        nuts: true,
        tags: ['coffee', 'pistachio', 'signature', 'nutty', 'seasonal'],
        seasonal: true,
        bestseller: true,
        rating: 4.9,
        ratingCount: 284,
        orderCount: 1520,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Kesar Badam Cortado',
        slug: 'kesar-badam-cortado',
        description: 'Saffron and almond milk reduced down, cut with a double ristretto.',
        basePrice: 290,
        image: IMG.cortado,
        calories: 210,
        prepTimeMinutes: 7,
        ingredients: ['house espresso blend', 'almond milk', 'Kashmiri saffron', 'cane sugar'],
        allergens: ['Tree nuts'],
        nuts: true,
        vegan: true,
        tags: ['coffee', 'saffron', 'almond', 'signature', 'indian'],
        isNew: true,
        chefSpecial: true,
        rating: 4.7,
        ratingCount: 128,
        orderCount: 640,
        modifiers: ['size', 'sweetness'],
      },
      {
        name: 'Malabar Coconut Cold Brew',
        slug: 'malabar-coconut-cold-brew',
        description: 'Cold brew over pressed coconut milk, lime leaf and a little palm sugar.',
        basePrice: 300,
        image: IMG.vanillaColdBrew,
        calories: 190,
        prepTimeMinutes: 5,
        ingredients: ['cold brew concentrate', 'coconut milk', 'lime leaf', 'palm sugar'],
        vegan: true,
        tags: ['coffee', 'cold brew', 'coconut', 'signature', 'seasonal', 'vegan'],
        seasonal: true,
        isNew: true,
        rating: 4.8,
        ratingCount: 156,
        orderCount: 780,
        modifiers: ['size', 'sweetness', 'iceLevel'],
      },
      {
        name: 'Jaggery Butterscotch Latte',
        slug: 'jaggery-butterscotch-latte',
        description: 'Palm jaggery cooked to butterscotch, stirred through a double-shot latte.',
        basePrice: 270,
        image: IMG.caramelLatte,
        calories: 320,
        prepTimeMinutes: 7,
        ingredients: ['house espresso blend', 'whole milk', 'palm jaggery', 'butter', 'sea salt'],
        allergens: ['Milk'],
        tags: ['coffee', 'jaggery', 'butterscotch', 'signature', 'sweet'],
        rating: 4.7,
        ratingCount: 184,
        orderCount: 960,
        modifiers: COFFEE_MODS,
      },
      {
        name: 'Matcha Cloud',
        slug: 'matcha-cloud',
        description: 'Cold-whisked matcha under a whipped coconut cloud and toasted white chocolate.',
        basePrice: 310,
        image: IMG.icedMatcha,
        calories: 300,
        prepTimeMinutes: 8,
        ingredients: ['Uji ceremonial matcha', 'coconut cream', 'white chocolate', 'ice'],
        allergens: ['Milk'],
        tags: ['matcha', 'signature', 'cold', 'seasonal', 'cloud'],
        seasonal: true,
        isNew: true,
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 168,
        orderCount: 820,
        modifiers: ['size', 'sweetness', 'matchaAddons'],
      },
      {
        name: 'Truffle Mushroom Toast',
        slug: 'truffle-mushroom-toast',
        description: 'Butter-roasted mushrooms and truffle cream on sourdough, with a soft egg.',
        basePrice: 470,
        image: IMG.mushroomMelt,
        calories: 580,
        prepTimeMinutes: 15,
        ingredients: ['wild mushrooms', 'truffle cream', 'sourdough', 'free-range egg', 'chives'],
        allergens: ['Gluten', 'Milk', 'Egg'],
        egg: true,
        gluten: true,
        tags: ['signature', 'truffle', 'mushroom', 'toast', 'brunch'],
        chefSpecial: true,
        bestseller: true,
        rating: 4.9,
        ratingCount: 264,
        orderCount: 1360,
        modifiers: ['bread', 'toastAddons'],
      },
      {
        name: 'Bombay Masala Grilled Cheese',
        slug: 'bombay-masala-grilled-cheese',
        description: 'Amul-style masala potato, green chutney and three cheeses, pressed hard.',
        basePrice: 390,
        image: IMG.grilledCheese,
        calories: 620,
        prepTimeMinutes: 13,
        ingredients: ['spiced potato', 'coriander chutney', 'cheddar', 'mozzarella', 'sourdough'],
        allergens: ['Gluten', 'Milk'],
        gluten: true,
        spicy: true,
        tags: ['signature', 'sandwich', 'masala', 'cheese', 'indian', 'spicy'],
        bestseller: true,
        rating: 4.8,
        ratingCount: 302,
        orderCount: 1640,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Chettinad Chicken Panini',
        slug: 'chettinad-chicken-panini',
        description: 'Chettinad-spiced chicken, curry leaf mayonnaise and red onion on ciabatta.',
        basePrice: 470,
        image: IMG.pestoPanini,
        calories: 680,
        prepTimeMinutes: 15,
        ingredients: ['chicken', 'Chettinad masala', 'curry leaf mayonnaise', 'red onion', 'ciabatta'],
        allergens: ['Gluten', 'Egg'],
        nonVeg: true,
        gluten: true,
        egg: true,
        spicy: true,
        tags: ['signature', 'sandwich', 'chicken', 'chettinad', 'spicy', 'indian'],
        chefSpecial: true,
        rating: 4.8,
        ratingCount: 218,
        orderCount: 1180,
        modifiers: ['bread', 'sandwichAddons'],
      },
      {
        name: 'Berry Cheesecake',
        slug: 'berry-cheesecake',
        description: 'Basque cheesecake under a sharp compote of blackberry, raspberry and hibiscus.',
        basePrice: 350,
        image: IMG.berryCheesecake,
        calories: 510,
        prepTimeMinutes: 6,
        ingredients: ['cream cheese', 'cream', 'blackberry', 'raspberry', 'hibiscus'],
        allergens: ['Egg', 'Milk'],
        egg: true,
        tags: ['dessert', 'signature', 'cheesecake', 'berry', 'seasonal'],
        seasonal: true,
        isNew: true,
        rating: 4.9,
        ratingCount: 196,
        orderCount: 940,
        modifiers: ['dessertAddons'],
      },
    ],
  },
];

// ─────────────────────────────────────────────────────── modifier groups

export interface SeedModifier {
  key: ModifierKey;
  name: string;
  description?: string;
  selectionType: 'SINGLE' | 'MULTI';
  isRequired: boolean;
  minSelect: number;
  maxSelect: number;
  options: { name: string; priceDelta: number; isDefault?: boolean }[];
}

export const MODIFIERS: SeedModifier[] = [
  {
    key: 'size',
    name: 'Size',
    selectionType: 'SINGLE',
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'Small', priceDelta: 0, isDefault: true },
      { name: 'Medium', priceDelta: 30 },
      { name: 'Large', priceDelta: 55 },
    ],
  },
  {
    key: 'milk',
    name: 'Milk',
    description: 'Plant milks are steamed on a separate wand.',
    selectionType: 'SINGLE',
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'Whole Milk', priceDelta: 0, isDefault: true },
      { name: 'Skimmed Milk', priceDelta: 0 },
      { name: 'Oat Milk', priceDelta: 60 },
      { name: 'Almond Milk', priceDelta: 60 },
      { name: 'Soy Milk', priceDelta: 50 },
    ],
  },
  {
    key: 'coffeeAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 4,
    options: [
      { name: 'Extra Espresso Shot', priceDelta: 50 },
      { name: 'Vanilla', priceDelta: 30 },
      { name: 'Caramel', priceDelta: 30 },
      { name: 'Hazelnut', priceDelta: 30 },
    ],
  },
  {
    key: 'sweetness',
    name: 'Sweetness',
    selectionType: 'SINGLE',
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'No Sugar', priceDelta: 0, isDefault: true },
      { name: 'Less Sweet', priceDelta: 0 },
      { name: 'Regular', priceDelta: 0 },
    ],
  },
  {
    key: 'iceLevel',
    name: 'Ice',
    selectionType: 'SINGLE',
    isRequired: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { name: 'Regular Ice', priceDelta: 0, isDefault: true },
      { name: 'Light Ice', priceDelta: 0 },
      { name: 'Extra Ice', priceDelta: 0 },
    ],
  },
  {
    key: 'teaStrength',
    name: 'Strength',
    selectionType: 'SINGLE',
    isRequired: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { name: 'Regular', priceDelta: 0, isDefault: true },
      { name: 'Light Brew', priceDelta: 0 },
      { name: 'Strong Brew', priceDelta: 0 },
    ],
  },
  {
    key: 'matchaAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 3,
    options: [
      { name: 'Extra Matcha Scoop', priceDelta: 70 },
      { name: 'Vanilla', priceDelta: 30 },
      { name: 'Wild Honey', priceDelta: 40 },
    ],
  },
  {
    key: 'toastAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 4,
    options: [
      { name: 'Poached Egg', priceDelta: 60 },
      { name: 'Greek Feta', priceDelta: 70 },
      { name: 'Smoked Chicken', priceDelta: 140 },
      { name: 'Chilli Flakes', priceDelta: 0 },
    ],
  },
  {
    key: 'bread',
    name: 'Bread',
    selectionType: 'SINGLE',
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'Sourdough', priceDelta: 0, isDefault: true },
      { name: 'Multigrain', priceDelta: 0 },
      { name: 'Ciabatta', priceDelta: 20 },
      { name: 'Gluten-Free', priceDelta: 60 },
    ],
  },
  {
    key: 'eggStyle',
    name: 'Eggs',
    selectionType: 'SINGLE',
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'Poached', priceDelta: 0, isDefault: true },
      { name: 'Scrambled', priceDelta: 0 },
      { name: 'Fried', priceDelta: 0 },
    ],
  },
  {
    key: 'pastaAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 4,
    options: [
      { name: 'Add Chicken', priceDelta: 100 },
      { name: 'Add Mushroom', priceDelta: 70 },
      { name: 'Extra Parmesan', priceDelta: 50 },
      { name: 'Extra Truffle Oil', priceDelta: 90 },
    ],
  },
  {
    key: 'pastaSpice',
    name: 'Spice',
    selectionType: 'SINGLE',
    isRequired: false,
    minSelect: 0,
    maxSelect: 1,
    options: [
      { name: 'Mild', priceDelta: 0, isDefault: true },
      { name: 'Medium', priceDelta: 0 },
      { name: 'Hot', priceDelta: 0 },
    ],
  },
  {
    key: 'sandwichAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 4,
    options: [
      { name: 'Extra Cheese', priceDelta: 50 },
      { name: 'Add Avocado', priceDelta: 80 },
      { name: 'Add Fried Egg', priceDelta: 40 },
      { name: 'Add Smoked Chicken', priceDelta: 140 },
    ],
  },
  {
    key: 'saladDressing',
    name: 'Dressing',
    selectionType: 'SINGLE',
    isRequired: true,
    minSelect: 1,
    maxSelect: 1,
    options: [
      { name: 'House Vinaigrette', priceDelta: 0, isDefault: true },
      { name: 'Caesar', priceDelta: 0 },
      { name: 'Aged Balsamic', priceDelta: 0 },
      { name: 'Lemon & Olive Oil', priceDelta: 0 },
    ],
  },
  {
    key: 'saladAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 3,
    options: [
      { name: 'Add Grilled Chicken', priceDelta: 140 },
      { name: 'Add Burrata', priceDelta: 160 },
      { name: 'Add Avocado', priceDelta: 80 },
    ],
  },
  {
    key: 'dessertAddons',
    name: 'Add-ons',
    selectionType: 'MULTI',
    isRequired: false,
    minSelect: 0,
    maxSelect: 3,
    options: [
      { name: 'Vanilla Bean Gelato', priceDelta: 90 },
      { name: 'Berry Compote', priceDelta: 60 },
      { name: 'Toasted Hazelnuts', priceDelta: 50 },
    ],
  },
];
